### ISSUE TITLE
推荐我的微服务开源项目！！😁

### ISSUE THREAD

**Issue by xlvchao** [CodingDocs/awesome-java#22]
https://github.com/xlvchao/spartacus

spartacus是一个基于Spring Boot 2.3.x、Spring Cloud Hoxton.SR5、Spring Security 2.3.x、OAuth2.0、Python3等开源框架构建的分布式系统，亦是一个功能完备的微服务开发脚手架。

**Comment by Snailclimb** [comment]
> https://github.com/xlvchao/spartacus
> 
> spartacus是一个基于Spring Boot 2.3.x、Spring Cloud Hoxton.SR5、Spring Security 2.3.x、OAuth2.0、Python3等开源框架构建的分布式系统，亦是一个功能完备的微服务开发脚手架。

看着还不错啊👍大佬的作品啊，厉害了

**Comment by jerriliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
