### ISSUE TITLE
有个地方需要改一下

### ISSUE THREAD

**Issue by wenjiu23** [CodingDocs/awesome-java#28]
![image](https://github.com/CodingDocs/awesome-java/assets/121745084/0f75d6f9-9d49-493e-8ef0-c9845c9744c2)

**Comment by jerriliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/121745084/260287120-0f75d6f9-9d49-493e-8ef0-c9845c9744c2.png)

我这里显示没问题：https://javaguide.cn/java/collection/arraylist-source-code.html ，不好复现，检查一下浏览器和链接是否是最近的。

<img width="1434" alt="image" src="https://github.com/CodingDocs/awesome-java/assets/29880145/6ae54468-4fc9-4f35-bb19-900b279542d5">
