### ISSUE TITLE
麻烦javaguide列出文章的时候，尽可能给一下更新的时间，这样也好做版本回溯，并且也可以借此判断信息的时效性

### ISSUE THREAD

**Issue by hwfancyz7k** [CodingDocs/awesome-java#33]

**Comment by jerriliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Snailclimb** [comment]
> _No description provided._

网站文章底部有更新日期，看这个就够了：

<img width="1249" alt="image" src="https://github.com/CodingDocs/awesome-java/assets/29880145/11aada5e-07e1-4192-89f7-aa400a630957">
